Automatically detect the top_module from the filename

diff --git a/verilog/tools/synth_aig b/verilog/tools/synth_aig
--- a/verilog/tools/synth_aig
+++ b/verilog/tools/synth_aig
@@ -1,15 +1,30 @@
 #!/usr/bin/env bash
-# FIXME convert systemverilog to verilog before synthesis
+
+# Check the arguments
+if ! [[ $# -eq 1 ]] 
+then
+    echo "Usage: synth_aig <verilog or systemVerilog top file>"
+    exit 1
+fi
+
+# Get the module's name from the path and convert systemVerilog to verilog if
+# needed
 HDL_FULLPATH=`realpath $1`
+TOP_MODULE=`basename ${HDL_FULLPATH%%.*}` # remove the extension and the path
+echo "Top level name is expected to be: $TOP_MODULE"
 if [[ $1 == *.sv ]]
 then
     echo "Translating SystemVerilog to verilog"
     sv2v --define=SYNTHESIS $HDL_FULLPATH > ${HDL_FULLPATH}.v
     HDL_FULLPATH="${HDL_FULLPATH}.v"
 fi
+
+# Generate the And Inverter graph
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 cd $SCRIPT_DIR
-TOPLEVEL="$2" VLOG_FILE_NAME=$HDL_FULLPATH yosys yosys_aig.tcl
+TOPLEVEL="$TOP_MODULE" VLOG_FILE_NAME=$HDL_FULLPATH yosys yosys_aig.tcl
+
+# Cleanup
 if [[ $1 == *.sv ]]
 then
     echo "Deleting generated ${HDL_FULLPATH}"
